---
title: "Week4_hw"
author: "Soki Kimura"
date: "2023-10-25"
output: html_document
---

# Packages

```{r}
library(tidyverse)
library(readr)
library(sf)
library(countrycode)

```


# Load Data
```{r}
# source: https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-0.002619%2C0.000000%2C1.00
world_map <- st_read("Data/World_Countries_Generalized.geojson")

# source: https://hdr.undp.org/sites/default/files/2021-22_HDR/HDR21-22_Composite_indices_complete_time_series.csv
gii_table <- read_csv("Data/HDR21-22_Composite_indices_complete_time_series.csv") %>%
  dplyr::select(., iso3, country, contains("gii"))
```

# Analyze data

```{r}

# Create ISO-2 character for merging with map data, and
# calculate the difference between 2019 and 2010
gii_table2 <- gii_table %>%
  dplyr::mutate(
    .,
    iso2c = countrycode(iso3, origin = "iso3c", destination = "iso2c"),
    .before = country
  ) %>%
  dplyr::mutate(
    .,
    gii_diff = gii_2019 - gii_2010,
    .after = country
  )

# Join map data with statistics
gii_map <- world_map %>%
  left_join(
    .,
    gii_table2,
    by = c("ISO" = "iso2c")
  )


```

# create map

```{r}

ggplot(data = gii_map) +
  geom_sf(
    aes(fill = gii_diff)
  ) + 
  ggtitle("GII Difference between 2010 and 2019")

```


