---
title: "Week3 Practical"
author: "Soki Kimura"
date: "2023-10-18"
output: html_document
---

# libraries

```{r}
library(sf)
library(terra)
library(fs)
library(tidyverse)
library(ggplot2)
library(plotly)
```

# load data

```{r}

st_layers("Data/gadm36_AUS.gpkg")
Aus_outline <- st_read("Data/gadm36_AUS.gpkg",
        layer = 'gadm36_AUS_0')

Aus_outline_proj <- Aus_outline %>%
  st_transform(., 3112)
print(Aus_outline_proj)

jan <- terra::rast("Data/wc2.1_5m_tavg/wc2.1_5m_tavg_01.tif")


```

# projections

```{r}
plot(jan)

pr1 <- terra::project(jan,"ESRI:54009")

plot(pr1)

```

```{r}

# list file paths
listfiles <- dir_info("Data/wc2.1_5m_tavg") %>%
  filter(str_detect(path,".tif")) %>%
  dplyr::select(path) %>%
  pull()

# load raster files
world_temp <- listfiles %>%
  terra::rast(.)

# rename
month <- c("Jan","Feb","Mar","Apr","May","Jun",
           "Jul","Aug","Sep","Oct","Nov","Dec")
names(world_temp) <- month

world_temp$Jan

```

# extract data

```{r}

site <- c("Brisbane", "Melbourne", "Perth", "Sydney", "Broome", "Darwin", "Orange", 
          "Bunbury", "Cairns", "Adelaide", "Gold Coast", "Canberra", "Newcastle", 
          "Wollongong", "Logan City" )
lon <- c(153.03, 144.96, 115.86, 151.21, 122.23, 130.84, 149.10, 115.64, 145.77, 
         138.6, 153.43, 149.13, 151.78, 150.89, 153.12)
lat <- c(-27.47, -37.91, -31.95, -33.87, 17.96, -12.46, -33.28, -33.33, -16.92, 
         -34.93, -28, -35.28, -32.93, -34.42, -27.64)

#Put all of this information into one list 
samples <- data.frame(site,lon,lat,row.names="site")

# Extract the data from the Rasterstack for all points 
AUcitytemp <- terra::extract(world_temp,samples)

AUcitytemp2 <- AUcitytemp %>%
  as_tibble(.) %>%
  add_column(Site = site, .before = "Jan")

```

# descriptive statistics (histogram)

```{r}

# take Perth as example
Perth_temp <- AUcitytemp2 %>%
  filter(site == "Perth")

# filter only the temperature
t <- Perth_temp %>%
  dplyr::select(Jan:Dec)

userbreak <- c(8,10,12,14,16,18,20,22,24,26)

# make histogram
hist(as.numeric(t),
     breaks = userbreak,
     col = "red",
     main = "Histogram of Perth Temperature",
     xlab = "Temperature",
     ylab = "Frequency")

# check information
histinfo <- as.numeric(t) %>%
  as.numeric(.) %>%
  hist(.)

histinfo

```

# Histogram for Australia

```{r}

Aus_simple <- Aus_outline %>%
  st_simplify(., dTolerance = 1000) %>%
  st_geometry() %>%
  plot()

# check CRS
# print(Aus_outline)
# crs(world_temp)

Aus_temp <- Aus_outline %>%
  terra::crop(world_temp, .)

exact <- terra::mask(Aus_temp, Aus_outline)

hist(exact[[3]],col="red",main ="Temperature in March")

```

# using ggplot

```{r}
exact_df <- exact %>%
  as.data.frame(.)

# set up histogram
gghist <- ggplot(exact_df, aes(x=Mar)) +
  geom_histogram(color = "black",
                 fill = "white") + 
  labs(title = "ggplot2 histogram of Australian March temperatures",
       x = "Temperature",
       y = "Frequency")

# add a vertical line showing mean temperature
gghist + 
  geom_vline(aes(xintercept = mean(Mar, na.rm = TRUE)),
                  color = "blue",
                  linetype = "dashed",
                  linewidth = 1) + 
  theme(plot.title = element_text(hjust = 0.5))


```
# multiple months into single histogram

```{r}
squish_data <- exact_df %>%
  pivot_longer(cols = 1:12,
               names_to = "Month",
               values_to = "Temp")

# extract 2 months
two_months <- squish_data %>%
  filter(., Month == "Jan" | Month == "Jun")


# get average na.rm removes the n/a data
mean_two_months <- two_months %>%
  group_by(., Month) %>%
  summarise(mean = mean(Temp, na.rm = TRUE))

ggplot(two_months, aes(x = Temp, color = Month, fill = Month)) +
  geom_histogram(position = "identity", alpha = 0.5) + 
  geom_vline(data = mean_two_months,
             aes(xintercept = mean,
                 color = Month),
             linetype = "dashed") + 
  labs(title = "ggplot2 histogram of Australian Jan and June temperatures",
       x = "Temperature",
       y = "Frequency") + 
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

```

# histogram with all months 
```{r}

# make months into factor
data_complete_cases <- squish_data %>%
  drop_na() %>%
  mutate(Month = factor(Month, levels = c("Jan","Feb","Mar","Apr","May","Jun",
                                          "Jul","Aug","Sep","Oct","Nov","Dec")))

# Plot histogram
ggplot(data_complete_cases, aes(x=Temp, na.rm=TRUE)) +
  geom_histogram(color = "black", binwidth = 5) + 
  labs(title = "ggplot faceted histogram of Australian Temperatures",
       x = "Temperature",
       y = "Frequency") + 
  facet_grid(Month ~ .) +
  theme(plot.title = element_text(hjust = 0.5))


```
# use plotly
```{r}

jan <- squish_data %>%
  drop_na(.) %>%
  filter(., Month == "Jan")
jun <- squish_data %>%
  drop_na(.) %>%
  filter(., Month == "Jun")

# axis titles
x_axis <- list(title = "Temperature")
y_axis <- list(title = "Frequency")

# set bin width
xbinsno <- list(start = 0, end = 40, size = 2.5)

ihist <- plot_ly(alpha = 0.6) %>%
  add_histogram(x = jan$Temp,
                xbins = xbinsno,
                name = "January") %>%
  add_histogram(x = jun$Temp,
                xbins = xbinsno,
                name = "June") %>%
  layout(barmode = "overlay", xaxis = x_axis, yaxis = y_axis)

ihist







```

# other descriptive statistics

```{r}
# mean per month
mean_all <- data_complete_cases %>%
  group_by(Month) %>%
  summarise(mean = mean(Temp, na.rm = TRUE))

# standard deviation
stdev_all <- data_complete_cases %>%
  group_by(Month) %>%
  summarise(sd = sd(Temp, na.rm = TRUE))

# max, min, interquartile range
range_all <- data_complete_cases %>%
  group_by(Month) %>%
  summarise(max = max(Temp, na.rm = TRUE),
            min = min(Temp, na.rm = TRUE),
            IQR = IQR(Temp, na.rm = TRUE))

mean_whole <- data_complete_cases %>%
  summarise(meanyear = mean(Temp, na.rm = TRUE))
mean_whole


```



